/* NetHack may be freely redistributed.  See license for details. */

/* attkbpdefs: generates src/attkbp.c, the attack->body-part attribution
 * table. Built and run strictly after include/pm.h exists; see GNUmakefile.
 */

#include "config.h"
#include "permonst.h"
#include "pm.h"
#include "mondata.h"
#include "mattkbp.h"
#include "atkbpnames.h"

#include <stdlib.h>
#include <string.h>

#define Fprintf (void) fprintf
#define Fclose  (void) fclose

static const char *Dont_Edit_Code =
    "/* This source file is generated by 'attkbpdefs'.  Do not edit. */\n";

/* returns a static buffer holding `bits` written out as a valid C
 * initializer for a struct atkbp_set, one designated word entry per word,
 * each word's value a symbolic OR-expression (e.g. "ATKBP_BIT_ARM|
 * ATKBP_BIT_ARM_3RD") or plain "0" if that word is empty -- used so the
 * generated attkbp.c is human-readable/auditable rather than a wall of raw
 * hex, while still being a valid file-scope constant expression.
 */
static char *
atkbp_bits_to_string(struct atkbp_set bits)
{
    static char buf[BUFSZ];
    char word_expr[ATKBP_NWORDS][BUFSZ];
    boolean word_used[ATKBP_NWORDS];
    int i, w;

    for (w = 0; w < ATKBP_NWORDS; w++) {
	word_expr[w][0] = '\0';
	word_used[w] = FALSE;
    }
    for (i = 0; atkbp_name_list[i].name; i++) {
	w = atkbp_name_list[i].word;
	if (atkbp_name_list[i].bit != 0L
	    && (bits.w[w] & atkbp_name_list[i].bit) == atkbp_name_list[i].bit) {
	    char namebuf[BUFSZ];

	    Sprintf(namebuf, "ATKBP_BIT_%s", atkbp_name_list[i].name);
	    if (word_used[w])
		Strcat(word_expr[w], "|");
	    Strcat(word_expr[w], namebuf);
	    word_used[w] = TRUE;
	}
    }

    Strcpy(buf, "{ .w = {");
    for (w = 0; w < ATKBP_NWORDS; w++) {
	char numbuf[QBUFSZ];

	if (w > 0)
	    Strcat(buf, ",");
	Sprintf(numbuf, " [%d] = %s", w, word_used[w] ? word_expr[w] : "0");
	Strcat(buf, numbuf);
    }
    Strcat(buf, " } }");
    return buf;
}

/* vague/unordinaled bits are dropped in favor of whatever concrete limb
 * identity a different attack (or mon_flag_bodyparts()) establishes
 * instead -- except under INNUMERABLE, where there's no concrete count to
 * defer to (e.g. Legion's mass of arms).
 */
static struct atkbp_set
mon_bodypart_bits(struct atkbp_set attk_bits)
{
    struct atkbp_set vague_mask = atkbp_or((struct atkbp_set[]){
	ATKBP(ARM), ATKBP(LEG), ATKBP(ARM_LOWER), ATKBP(LEG_REAR), ATKBP(LEG_FRONT), ATKBP(NONE) });
    struct atkbp_set always_drop = atkbp_or((struct atkbp_set[]){
	ATKBP(WHOLE_BODY), ATKBP(MIND_NOLIMB), ATKBP(INNUMERABLE), ATKBP(NONE) });
    struct atkbp_set result = attk_bits;
    int i;

    if (!atkbp_intersects(attk_bits, ATKBP(INNUMERABLE)))
	for (i = 0; i < ATKBP_NWORDS; i++)
	    result.w[i] &= ~vague_mask.w[i];
    for (i = 0; i < ATKBP_NWORDS; i++)
	result.w[i] &= ~always_drop.w[i];
    return result;
}

static void
do_attkbp(void)
{
    register struct permonst *ptr;
    register int i;
    struct atkbp_set resolved[NATTK];
    int nattk;
    boolean ordinal_overflow;
    FILE *ofp;

    ofp = fopen("../src/attkbp.c", "w");
    if (!ofp) {
	perror("../src/attkbp.c");
	exit(EXIT_FAILURE);
    }
    Fprintf(ofp,"%s",Dont_Edit_Code);
    Fprintf(ofp,"#include \"config.h\"\n");
    Fprintf(ofp,"#include \"permonst.h\"\n");
    Fprintf(ofp,"#include \"pm.h\"\t/* NUMMONS, for attkbp_init() below */\n");
    Fprintf(ofp,"#include \"mondata.h\"\n");
    Fprintf(ofp,"#include \"mattkbp.h\"\n");
    Fprintf(ofp,"\nstruct mon_atkbp attkbp[] = {\n");
    for (ptr = &mons[0]; ptr->mlet; ptr++) {
#define MB_PARTS_SLOT 1
#define MAX_ALT_ATTACK_SET 1
	struct atkbp_set bodyparts[NATTK + MAX_ALT_ATTACK_SET + MB_PARTS_SLOT + 1];

	/* attk_bodyparts_all(), not attk_bodyparts() directly, is needed here
	 * for whole-attack-list-aware cases (AT_SQUZ/AT_MARI/AT_MSPR/AT_MAGC/
	 * AT_MMGC). Real mons[] data is fixed build-time content -- an
	 * ordinal overflow here is a real data problem, so fail the build
	 * loudly instead of degrading gracefully.
	 */
	nattk = attk_bodyparts_all(ptr, resolved, &ordinal_overflow);
	if (ordinal_overflow) {
	    Fprintf(stderr,
		"do_attkbp: %s has more simultaneous extra (AT_MARI/AT_MSPR) "
		"arms than attk_bodyparts_all() can assign an ordinal "
		"identity to; add another ATKBP_ARM_*TH bit to "
		"include/mattkbp.h and extra_arm_bits[] (src/mattkbp.c)\n",
		ptr->mname);
	    exit(EXIT_FAILURE);
	}

	/* bodyparts: the union of every attack resolved above (filtered to
	 * specific limbs only, mon_bodypart_bits()) plus whatever
	 * mon_flag_bodyparts() can tell from flags alone -- filtering can
	 * legitimately zero out an attack's contribution entirely (e.g.
	 * housecat's single claw, whose only bit was the now-excluded
	 * LEG_FRONT).
	 */
	{
	    struct atkbp_set filtered;
	    int nbp = 0;

	    for (i = 0; i < nattk; i++) {
			filtered = mon_bodypart_bits(resolved[i]);
			if (!atkbp_is_none(filtered))
				bodyparts[nbp++] = filtered;
	    }
	    filtered = mon_flag_bodyparts(ptr);
	    if (!atkbp_is_none(filtered))
		bodyparts[nbp++] = filtered;
	    /* Lolth's real mattk[] alone doesn't reveal she has up to 8 arms --
	     * only her alternate "marilith-hands" routine (lolth_alt_attacks[])
	     * does. She has them regardless of whether that form gets rolled,
	     * so fold the same bits into her body-plan summary here.
	     */
	    if (ptr->mtyp == PM_AVATAR_OF_LOLTH) {
		struct atkbp_set lolth_alt[LOLTH_ALT_ATTACK_COUNT + 1];
		int li;

		for (li = 0; li < LOLTH_ALT_ATTACK_COUNT; li++)
		    lolth_alt[li] = lolth_alt_bodypart(li);
		lolth_alt[LOLTH_ALT_ATTACK_COUNT] = ATKBP(NONE);
		filtered = atkbp_or(lolth_alt);
		if (!atkbp_is_none(filtered))
		    bodyparts[nbp++] = filtered;
	    }
	    bodyparts[nbp] = ATKBP(NONE);
	}

	Fprintf(ofp,"/* %s */\n{\n\t{\n", ptr->mname);
	for (i = 0; i < nattk; i++)
	    Fprintf(ofp,"\t\t%s,\n", atkbp_bits_to_string(resolved[i]));
	Fprintf(ofp,"\t},\n\t%s\n},\n", atkbp_bits_to_string(atkbp_or(bodyparts)));
    }
    Fprintf(ofp,"};\n");

    /* attkbp_init(): copies this file's attkbp[] table into mons[]'s own
     * mattk[].bodypart fields (include/permonst.h) at game startup, so
     * every consumer can read attribution straight off the struct attack
     * it already has in hand rather than going through a separate lookup.
     * attkbp[] is indexed the same way mons[] is, so this is a direct
     * element-wise copy -- no dependency on mons[i].mtyp having already
     * been stamped (id_permonst()) first.
     */
    Fprintf(ofp,"\nvoid NDECL(attkbp_init);\n");
    Fprintf(ofp,"\nvoid\n");
    Fprintf(ofp,"attkbp_init()\n");
    Fprintf(ofp,"{\n");
    Fprintf(ofp,"    int i, j;\n\n");
    Fprintf(ofp,"    for (i = 0; i < NUMMONS; i++)\n");
    Fprintf(ofp,"\tfor (j = 0; j < NATTK; j++)\n");
    Fprintf(ofp,"\t    mons[i].mattk[j].bodypart = attkbp[i].attacks[j];\n");
    Fprintf(ofp,"}\n");
    Fprintf(ofp,"\n/*attkbp.c*/\n");

    Fclose(ofp);
}

/* src/xhity.c's getattk() splices blib_alt_attacks[] (include/mattkbp.h,
 * defined in src/mattkbp.c) into Blibdoolpoolp's high-Insight alternate
 * attack routine, deriving each entry's .bodypart from her *real* mattk[]
 * at the corresponding BLIB_ALT_REAL_INDEX() rather than a second
 * hand-typed copy. That only stays correct as long as her real attack
 * list still has the shape blib_alt_attacks[] assumes -- fail the build
 * here, loudly, the moment it doesn't, rather than let xhity.c silently
 * misattribute (or index past her real attack count) at runtime.
 */
static void
check_blib_alt_shape(void)
{
    struct permonst *ptr = &mons[PM_BLIBDOOLPOOLP__GRAVEN_INTO_FLESH];
    int i, real_i;

    for (i = 0; i < BLIB_ALT_ATTACK_COUNT; i++) {
	real_i = BLIB_ALT_REAL_INDEX(i);
	if (real_i < 0)
	    continue;	/* the spliced-in AT_REND, no real analog */
	if (is_null_attk(&ptr->mattk[real_i])
	    || ptr->mattk[real_i].aatyp != blib_alt_attacks[i].aatyp) {
	    Fprintf(stderr,
		"check_blib_alt_shape: %s's real attack %d no longer has the "
		"shape blib_alt_attacks[] (src/mattkbp.c) assumes -- update "
		"both it and src/xhity.c's getattk().\n", ptr->mname, real_i);
	    exit(EXIT_FAILURE);
	}
    }
    /* she shouldn't have gained a real attack blib_alt_attacks[] doesn't
     * account for -- the last real index it maps to is 5 (blib index 6)
     */
    if (!is_null_attk(&ptr->mattk[6])) {
	Fprintf(stderr,
	    "check_blib_alt_shape: %s gained a new real attack that "
	    "blib_alt_attacks[] (src/mattkbp.c) doesn't account for -- "
	    "update it and src/xhity.c's getattk().\n", ptr->mname);
	exit(EXIT_FAILURE);
    }
}

int
main(void)
{
    int i;

    atkbp_assign_bits();

    /* attk_bodyparts() -> is_mind_flayer() needs mons[i].mtyp populated
     * (species template's own PM_ index) -- normally done at game startup
     * by id_permonst() (src/mondata.c), which this standalone tool doesn't
     * link (it pulls in "hack.h" and the rest of the game). Same two-line
     * effect, done directly.
     */
    for (i = 0; i < NUMMONS; i++)
	mons[i].mtyp = i;

    do_attkbp();
    check_blib_alt_shape();
    return 0;
}

/*attkbpdefs.c*/
