/* NetHack may be freely redistributed.  See license for details. */

/* attkbpdefs: generates src/attkbp.c, the attack->body-part attribution
 * table. Built and run strictly after include/pm.h exists; see GNUmakefile.
 */

#include "config.h"
#include "permonst.h"
#include "pm.h"
#include "mondata.h"
#include "mattkbp.h"
#include "atkbpnames.h"

#include <stdlib.h>
#include <string.h>

#define Fprintf (void) fprintf
#define Fclose  (void) fclose

static const char *Dont_Edit_Code =
    "/* This source file is generated by 'attkbpdefs'.  Do not edit. */\n";

/* returns a static buffer holding `bits` written out as a valid C
 * initializer for a struct atkbp_set, one designated word entry per word,
 * each word's value a symbolic OR-expression (e.g. "ATKBP_BIT_ARM|
 * ATKBP_BIT_ARM_3RD") or plain "0" if that word is empty -- used so the
 * generated attkbp.c is human-readable/auditable rather than a wall of raw
 * hex, while still being a valid file-scope constant expression.
 */
static char *
atkbp_bits_to_string(struct atkbp_set bits)
{
    static char buf[BUFSZ];
    char word_expr[ATKBP_NWORDS][BUFSZ];
    boolean word_used[ATKBP_NWORDS];
    int i, w;

    for (w = 0; w < ATKBP_NWORDS; w++) {
	word_expr[w][0] = '\0';
	word_used[w] = FALSE;
    }
    for (i = 0; atkbp_name_list[i].name; i++) {
	w = atkbp_name_list[i].word;
	if (atkbp_name_list[i].bit != 0L
	    && (bits.w[w] & atkbp_name_list[i].bit) == atkbp_name_list[i].bit) {
	    char namebuf[BUFSZ];

	    Sprintf(namebuf, "ATKBP_BIT_%s", atkbp_name_list[i].name);
	    if (word_used[w])
		Strcat(word_expr[w], "|");
	    Strcat(word_expr[w], namebuf);
	    word_used[w] = TRUE;
	}
    }

    Strcpy(buf, "{ .w = {");
    for (w = 0; w < ATKBP_NWORDS; w++) {
	char numbuf[QBUFSZ];

	if (w > 0)
	    Strcat(buf, ",");
	Sprintf(numbuf, " [%d] = %s", w, word_used[w] ? word_expr[w] : "0");
	Strcat(buf, numbuf);
    }
    Strcat(buf, " } }");
    return buf;
}

static void
do_attkbp(void)
{
    register struct permonst *ptr;
    register int i;
    struct atkbp_set resolved[NATTK];
    int nattk;
    boolean ordinal_overflow;
    FILE *ofp;

    ofp = fopen("../src/attkbp.c", "w");
    if (!ofp) {
	perror("../src/attkbp.c");
	exit(EXIT_FAILURE);
    }
    Fprintf(ofp,"%s",Dont_Edit_Code);
    Fprintf(ofp,"#include \"config.h\"\n");
    Fprintf(ofp,"#include \"permonst.h\"\n");
    Fprintf(ofp,"#include \"pm.h\"\t/* NUMMONS, for attkbp_init() below */\n");
    Fprintf(ofp,"#include \"mondata.h\"\n");
    Fprintf(ofp,"#include \"mattkbp.h\"\n");
    Fprintf(ofp,"\nstruct mon_atkbp attkbp[] = {\n");
    for (ptr = &mons[0]; ptr->mlet; ptr++) {
	/* attk_bodyparts_all(), not attk_bodyparts() directly, is needed here
	 * for whole-attack-list-aware cases (AT_SQUZ/AT_MARI/AT_MSPR/AT_MAGC/
	 * AT_MMGC). Real mons[] data is fixed build-time content -- an
	 * ordinal overflow here is a real data problem, so fail the build
	 * loudly instead of degrading gracefully.
	 */
	nattk = attk_bodyparts_all(ptr, resolved, &ordinal_overflow);
	if (ordinal_overflow) {
	    Fprintf(stderr,
		"do_attkbp: %s has more simultaneous extra (AT_MARI/AT_MSPR) "
		"arms than attk_bodyparts_all() can assign an ordinal "
		"identity to; add another ATKBP_ARM_*TH bit to "
		"include/mattkbp.h and extra_arm_bits[] (src/mattkbp.c)\n",
		ptr->mname);
	    exit(EXIT_FAILURE);
	}

	/* mon_bodyparts() reads each attack's own .bodypart field, so stamp the
	 * resolved values into this in-memory copy of mons[] first.
	 */
	for (i = 0; i < nattk; i++)
	    ptr->mattk[i].bodypart = resolved[i];

	Fprintf(ofp,"/* %s */\n{\n\t{\n", ptr->mname);
	for (i = 0; i < nattk; i++)
	    Fprintf(ofp,"\t\t%s,\n", atkbp_bits_to_string(resolved[i]));
	Fprintf(ofp,"\t},\n\t%s\n},\n", atkbp_bits_to_string(mon_bodyparts(ptr, INSIGHT_ALL)));
    }
    Fprintf(ofp,"};\n");

    /* attkbp_init(): copies this file's attkbp[] table into mons[]'s own
     * mattk[].bodypart and bodyparts fields (include/permonst.h) at game
     * startup, so every consumer can read attribution straight off the
     * struct attack (or permonst) it already has in hand rather than going
     * through a separate lookup. attkbp[] is indexed the same way mons[]
     * is, so this is a direct element-wise copy -- no dependency on
     * mons[i].mtyp having already been stamped (id_permonst()) first.
     */
    Fprintf(ofp,"\nvoid NDECL(attkbp_init);\n");
    Fprintf(ofp,"\nvoid\n");
    Fprintf(ofp,"attkbp_init()\n");
    Fprintf(ofp,"{\n");
    Fprintf(ofp,"    int i, j;\n\n");
    Fprintf(ofp,"    for (i = 0; i < NUMMONS; i++) {\n");
    Fprintf(ofp,"\tfor (j = 0; j < NATTK; j++)\n");
    Fprintf(ofp,"\t    mons[i].mattk[j].bodypart = attkbp[i].attacks[j];\n");
    Fprintf(ofp,"\tmons[i].bodyparts = attkbp[i].bodyparts;\n");
    Fprintf(ofp,"    }\n");
    Fprintf(ofp,"}\n");
    Fprintf(ofp,"\n/*attkbp.c*/\n");

    Fclose(ofp);
}

/* src/xhity.c's getattk() splices blib_alt_attacks[] (include/mattkbp.h,
 * defined in src/mattkbp.c) into Blibdoolpoolp's high-Insight alternate
 * attack routine, deriving each entry's .bodypart from her *real* mattk[]
 * at the corresponding BLIB_ALT_REAL_INDEX() rather than a second
 * hand-typed copy. That only stays correct as long as her real attack
 * list still has the shape blib_alt_attacks[] assumes -- fail the build
 * here, loudly, the moment it doesn't, rather than let xhity.c silently
 * misattribute (or index past her real attack count) at runtime.
 */
static void
check_blib_alt_shape(void)
{
    struct permonst *ptr = &mons[PM_BLIBDOOLPOOLP__GRAVEN_INTO_FLESH];
    int i, real_i;

    for (i = 0; i < BLIB_ALT_ATTACK_COUNT; i++) {
	real_i = BLIB_ALT_REAL_INDEX(i);
	if (real_i < 0)
	    continue;	/* the spliced-in AT_REND, no real analog */
	if (is_null_attk(&ptr->mattk[real_i])
	    || ptr->mattk[real_i].aatyp != blib_alt_attacks[i].aatyp) {
	    Fprintf(stderr,
		"check_blib_alt_shape: %s's real attack %d no longer has the "
		"shape blib_alt_attacks[] (src/mattkbp.c) assumes -- update "
		"both it and src/xhity.c's getattk().\n", ptr->mname, real_i);
	    exit(EXIT_FAILURE);
	}
    }
    /* she shouldn't have gained a real attack blib_alt_attacks[] doesn't
     * account for -- the last real index it maps to is 5 (blib index 6)
     */
    if (!is_null_attk(&ptr->mattk[6])) {
	Fprintf(stderr,
	    "check_blib_alt_shape: %s gained a new real attack that "
	    "blib_alt_attacks[] (src/mattkbp.c) doesn't account for -- "
	    "update it and src/xhity.c's getattk().\n", ptr->mname);
	exit(EXIT_FAILURE);
    }
}

int
main(void)
{
    int i;

    atkbp_assign_bits();

    /* attk_bodyparts() -> is_mind_flayer() needs mons[i].mtyp populated
     * (species template's own PM_ index) -- normally done at game startup
     * by id_permonst() (src/mondata.c), which this standalone tool doesn't
     * link (it pulls in "hack.h" and the rest of the game). Same two-line
     * effect, done directly.
     */
    for (i = 0; i < NUMMONS; i++)
	mons[i].mtyp = i;

    do_attkbp();
    check_blib_alt_shape();
    return 0;
}

/*attkbpdefs.c*/
